[package]
name = "greq"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
regex = "1.11.0"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }